[2024-11-07T07:12:42.807+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-07T07:12:42.869+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: series_tiempo_v01.extract_and_land manual__2024-11-07T07:12:41.605093+00:00 [queued]>
[2024-11-07T07:12:42.906+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: series_tiempo_v01.extract_and_land manual__2024-11-07T07:12:41.605093+00:00 [queued]>
[2024-11-07T07:12:42.907+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-07T07:12:42.943+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_and_land> on 2024-11-07 07:12:41.605093+00:00
[2024-11-07T07:12:42.963+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'series_tiempo_v01', 'extract_and_land', 'manual__2024-11-07T07:12:41.605093+00:00', '--job-id', '669', '--raw', '--subdir', 'DAGS_FOLDER/series_tiempo_dag.py', '--cfg-path', '/tmp/tmpvflcq1fh']
[2024-11-07T07:12:42.973+0000] {standard_task_runner.py:105} INFO - Job 669: Subtask extract_and_land
[2024-11-07T07:12:42.985+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=15288) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-07T07:12:42.986+0000] {standard_task_runner.py:72} INFO - Started process 15291 to run task
[2024-11-07T07:12:43.064+0000] {task_command.py:467} INFO - Running <TaskInstance: series_tiempo_v01.extract_and_land manual__2024-11-07T07:12:41.605093+00:00 [running]> on host 276004bbea2b
[2024-11-07T07:12:43.436+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='series_tiempo_v01' AIRFLOW_CTX_TASK_ID='extract_and_land' AIRFLOW_CTX_EXECUTION_DATE='2024-11-07T07:12:41.605093+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-07T07:12:41.605093+00:00'
[2024-11-07T07:12:43.438+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-07T07:12:53.145+0000] {logging_mixin.py:190} INFO - Error: [Errno 2] No such file or directory: "/opt/***/data/series_tiempo/<bound method ZipFile.namelist of <zipfile.ZipFile filename='/opt/***/data/series_tiempo/series_tiempo.zip' mode='r'>>" -> '/opt/***/data/series_tiempo/series_tiempo.csv'
[2024-11-07T07:12:53.145+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-07T07:12:53.155+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-07T07:12:53.155+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=series_tiempo_v01, task_id=extract_and_land, run_id=manual__2024-11-07T07:12:41.605093+00:00, execution_date=20241107T071241, start_date=20241107T071242, end_date=20241107T071253
[2024-11-07T07:12:53.217+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-07T07:12:53.236+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-07T07:12:53.238+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
