[2024-10-28T00:31:26.675+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-28T00:31:26.712+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: indices_argentina_v08.load scheduled__2024-10-27T00:00:00+00:00 [queued]>
[2024-10-28T00:31:26.731+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: indices_argentina_v08.load scheduled__2024-10-27T00:00:00+00:00 [queued]>
[2024-10-28T00:31:26.731+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-10-28T00:31:26.757+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load> on 2024-10-27 00:00:00+00:00
[2024-10-28T00:31:26.772+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'indices_argentina_v08', 'load', 'scheduled__2024-10-27T00:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp61vyegj_']
[2024-10-28T00:31:26.776+0000] {standard_task_runner.py:105} INFO - Job 216: Subtask load
[2024-10-28T00:31:26.785+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1423) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-28T00:31:26.786+0000] {standard_task_runner.py:72} INFO - Started process 1426 to run task
[2024-10-28T00:31:26.883+0000] {task_command.py:467} INFO - Running <TaskInstance: indices_argentina_v08.load scheduled__2024-10-27T00:00:00+00:00 [running]> on host 276004bbea2b
[2024-10-28T00:31:27.053+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='indices_argentina_v08' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-27T00:00:00+00:00'
[2024-10-28T00:31:27.054+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-28T00:31:39.523+0000] {logging_mixin.py:190} INFO - Error: The value of property spark.jars must not be null

JVM stacktrace:
java.lang.IllegalArgumentException: The value of property spark.jars must not be null
	at org.apache.hadoop.thirdparty.com.google.common.base.Preconditions.checkArgument(Preconditions.java:219)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1403)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1384)
	at org.apache.spark.sql.internal.SharedState.$anonfun$x$1$2(SharedState.scala:77)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:273)
	at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:69)
	at org.apache.spark.sql.SparkSession.$anonfun$sharedState$1(SparkSession.scala:143)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:143)
	at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:142)
	at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:162)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:160)
	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:157)
	at org.apache.spark.sql.DataFrameReader.<init>(DataFrameReader.scala:699)
	at org.apache.spark.sql.SparkSession.read(SparkSession.scala:783)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-28T00:31:39.713+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-28T00:31:39.739+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-28T00:31:39.740+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=indices_argentina_v08, task_id=load, run_id=scheduled__2024-10-27T00:00:00+00:00, execution_date=20241027T000000, start_date=20241028T003126, end_date=20241028T003139
[2024-10-28T00:31:40.060+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-28T00:31:40.094+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-28T00:31:40.104+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
