[2024-10-27T22:53:06.675+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-27T22:53:06.701+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: indices_argentina_v06.transform scheduled__2024-10-26T00:00:00+00:00 [queued]>
[2024-10-27T22:53:06.714+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: indices_argentina_v06.transform scheduled__2024-10-26T00:00:00+00:00 [queued]>
[2024-10-27T22:53:06.714+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 7
[2024-10-27T22:53:06.732+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform> on 2024-10-26 00:00:00+00:00
[2024-10-27T22:53:06.741+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'indices_argentina_v06', 'transform', 'scheduled__2024-10-26T00:00:00+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp6ntwnqxw']
[2024-10-27T22:53:06.747+0000] {standard_task_runner.py:105} INFO - Job 179: Subtask transform
[2024-10-27T22:53:06.748+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5550) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-27T22:53:06.749+0000] {standard_task_runner.py:72} INFO - Started process 5551 to run task
[2024-10-27T22:53:06.804+0000] {task_command.py:467} INFO - Running <TaskInstance: indices_argentina_v06.transform scheduled__2024-10-26T00:00:00+00:00 [running]> on host d9df5aecafce
[2024-10-27T22:53:07.076+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='indices_argentina_v06' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-26T00:00:00+00:00'
[2024-10-27T22:53:07.077+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-27T22:53:18.849+0000] {logging_mixin.py:190} INFO - Error: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `fecha` cannot be resolved. Did you mean one of the following? [`fecha_riesgo`, `valor_riesgo`].
[2024-10-27T22:53:19.119+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-27T22:53:19.130+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-27T22:53:19.131+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=indices_argentina_v06, task_id=transform, run_id=scheduled__2024-10-26T00:00:00+00:00, execution_date=20241026T000000, start_date=20241027T225306, end_date=20241027T225319
[2024-10-27T22:53:19.178+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-27T22:53:19.199+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-27T22:53:19.201+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
