[2024-11-08T21:19:42.419+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-08T21:19:42.440+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: plazo_fijo_v01.extract_and_land scheduled__2024-11-07T00:00:00+00:00 [queued]>
[2024-11-08T21:19:42.452+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: plazo_fijo_v01.extract_and_land scheduled__2024-11-07T00:00:00+00:00 [queued]>
[2024-11-08T21:19:42.452+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 7
[2024-11-08T21:19:42.470+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_and_land> on 2024-11-07 00:00:00+00:00
[2024-11-08T21:19:42.481+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'plazo_fijo_v01', 'extract_and_land', 'scheduled__2024-11-07T00:00:00+00:00', '--job-id', '720', '--raw', '--subdir', 'DAGS_FOLDER/plazo_fijo_dag.py', '--cfg-path', '/tmp/tmp28nk36ac']
[2024-11-08T21:19:42.484+0000] {standard_task_runner.py:105} INFO - Job 720: Subtask extract_and_land
[2024-11-08T21:19:42.485+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=11237) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-08T21:19:42.486+0000] {standard_task_runner.py:72} INFO - Started process 11238 to run task
[2024-11-08T21:19:42.540+0000] {task_command.py:467} INFO - Running <TaskInstance: plazo_fijo_v01.extract_and_land scheduled__2024-11-07T00:00:00+00:00 [running]> on host 276004bbea2b
[2024-11-08T21:19:42.797+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='plazo_fijo_v01' AIRFLOW_CTX_TASK_ID='extract_and_land' AIRFLOW_CTX_EXECUTION_DATE='2024-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-07T00:00:00+00:00'
[2024-11-08T21:19:42.798+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-08T21:19:43.137+0000] {logging_mixin.py:190} INFO - Error: [Errno 2] No such file or directory: '/opt/***/data/plazo_fijo/plazo_fijo.csv'
[2024-11-08T21:19:43.138+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-08T21:19:43.148+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-08T21:19:43.148+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=plazo_fijo_v01, task_id=extract_and_land, run_id=scheduled__2024-11-07T00:00:00+00:00, execution_date=20241107T000000, start_date=20241108T211942, end_date=20241108T211943
[2024-11-08T21:19:43.184+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-08T21:19:43.224+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-08T21:19:43.226+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
