[2024-10-28T22:19:18.317+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-28T22:19:18.338+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: indices_provincias_v01.inflacion_cordoba scheduled__2024-10-27T00:00:00+00:00 [queued]>
[2024-10-28T22:19:18.348+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: indices_provincias_v01.inflacion_cordoba scheduled__2024-10-27T00:00:00+00:00 [queued]>
[2024-10-28T22:19:18.349+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 7
[2024-10-28T22:19:18.363+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): inflacion_cordoba> on 2024-10-27 00:00:00+00:00
[2024-10-28T22:19:18.371+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'indices_provincias_v01', 'inflacion_cordoba', 'scheduled__2024-10-27T00:00:00+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/second_dag.py', '--cfg-path', '/tmp/tmpykcpjj0v']
[2024-10-28T22:19:18.374+0000] {standard_task_runner.py:105} INFO - Job 239: Subtask inflacion_cordoba
[2024-10-28T22:19:18.375+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4433) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-28T22:19:18.376+0000] {standard_task_runner.py:72} INFO - Started process 4434 to run task
[2024-10-28T22:19:18.427+0000] {task_command.py:467} INFO - Running <TaskInstance: indices_provincias_v01.inflacion_cordoba scheduled__2024-10-27T00:00:00+00:00 [running]> on host 276004bbea2b
[2024-10-28T22:19:18.664+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='indices_provincias_v01' AIRFLOW_CTX_TASK_ID='inflacion_cordoba' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-27T00:00:00+00:00'
[2024-10-28T22:19:18.664+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-28T22:19:30.899+0000] {logging_mixin.py:190} INFO - Error: [CANNOT_INFER_TYPE_FOR_FIELD] Unable to infer the type of the field `fecha_inflacion`.
[2024-10-28T22:19:31.056+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-28T22:19:31.069+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-28T22:19:31.070+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=indices_provincias_v01, task_id=inflacion_cordoba, run_id=scheduled__2024-10-27T00:00:00+00:00, execution_date=20241027T000000, start_date=20241028T221918, end_date=20241028T221931
[2024-10-28T22:19:31.124+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-28T22:19:31.144+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-28T22:19:31.146+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
