[2024-10-25T08:31:32.871+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T08:31:32.904+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: indices_argentina_v02.transform scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T08:31:32.923+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: indices_argentina_v02.transform scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T08:31:32.923+0000] {taskinstance.py:2865} INFO - Starting attempt 26 of 31
[2024-10-25T08:31:32.949+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform> on 2024-10-23 00:00:00+00:00
[2024-10-25T08:31:32.957+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T08:31:32.962+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20184) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-25T08:31:32.962+0000] {standard_task_runner.py:72} INFO - Started process 20284 to run task
[2024-10-25T08:31:32.963+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'indices_argentina_v02', 'transform', 'scheduled__2024-10-23T00:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpxvkg_7rw']
[2024-10-25T08:31:32.964+0000] {standard_task_runner.py:105} INFO - Job 127: Subtask transform
[2024-10-25T08:31:33.032+0000] {task_command.py:467} INFO - Running <TaskInstance: indices_argentina_v02.transform scheduled__2024-10-23T00:00:00+00:00 [running]> on host d9df5aecafce
[2024-10-25T08:31:33.366+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='indices_argentina_v02' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='26' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T00:00:00+00:00'
[2024-10-25T08:31:33.367+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T08:31:33.450+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2024-10-25T08:31:33.453+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T08:31:33.453+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2024-10-25T08:31:33.459+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T08:31:43.142+0000] {logging_mixin.py:190} INFO - +----------+-------------+-----------+
|     fecha|valor_mensual|valor_anual|
+----------+-------------+-----------+
|2024-09-30|          3.5|      209.0|
|2024-08-31|          4.2|      236.7|
|2024-07-31|          4.0|      263.4|
|2024-06-30|          4.6|      271.5|
|2024-05-31|          4.2|      276.4|
|2024-04-30|          8.8|      289.4|
|2024-03-31|         11.0|      287.9|
|2024-02-29|         13.2|      276.2|
|2024-01-31|         20.6|      254.2|
|2023-12-31|         25.5|      211.4|
|2023-11-30|         12.8|      160.9|
|2023-10-31|          8.3|      142.7|
|2023-09-30|         12.7|      138.3|
|2023-08-31|         12.4|      124.4|
|2023-07-31|          6.3|      113.4|
|2023-06-30|          6.0|      115.6|
|2023-05-31|          7.8|      114.2|
|2023-04-30|          8.4|      108.8|
|2023-03-31|          7.7|      104.3|
|2023-02-28|          6.6|      102.5|
+----------+-------------+-----------+
only showing top 20 rows
[2024-10-25T08:31:45.347+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-25T08:31:45.366+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T08:31:45.367+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=indices_argentina_v02, task_id=transform, run_id=scheduled__2024-10-23T00:00:00+00:00, execution_date=20241023T000000, start_date=20241025T083132, end_date=20241025T083145
[2024-10-25T08:31:45.436+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-25T08:31:45.462+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-25T08:31:45.464+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
