[2024-10-25T08:28:18.439+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T08:28:18.460+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: indices_argentina_v02.transform scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T08:28:18.472+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: indices_argentina_v02.transform scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T08:28:18.472+0000] {taskinstance.py:2865} INFO - Starting attempt 25 of 30
[2024-10-25T08:28:18.491+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform> on 2024-10-23 00:00:00+00:00
[2024-10-25T08:28:18.499+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T08:28:18.504+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'indices_argentina_v02', 'transform', 'scheduled__2024-10-23T00:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp4d58zrcs']
[2024-10-25T08:28:18.507+0000] {standard_task_runner.py:105} INFO - Job 124: Subtask transform
[2024-10-25T08:28:18.510+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18790) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-25T08:28:18.511+0000] {standard_task_runner.py:72} INFO - Started process 18967 to run task
[2024-10-25T08:28:18.563+0000] {task_command.py:467} INFO - Running <TaskInstance: indices_argentina_v02.transform scheduled__2024-10-23T00:00:00+00:00 [running]> on host d9df5aecafce
[2024-10-25T08:28:18.661+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2024-10-25T08:28:18.663+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T08:28:18.663+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2024-10-25T08:28:18.666+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-25T08:28:18.825+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rolo' AIRFLOW_CTX_DAG_ID='indices_argentina_v02' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='25' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T00:00:00+00:00'
[2024-10-25T08:28:18.826+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T08:28:29.034+0000] {logging_mixin.py:190} INFO - +----------+-------------+-----------+
|     fecha|valor_mensual|valor_anual|
+----------+-------------+-----------+
|2018-07-31|          3.1|       31.2|
|2018-08-31|          3.9|       34.4|
|2018-09-30|          6.5|       40.5|
|2018-10-31|          5.4|       45.9|
|2018-11-30|          3.2|       48.5|
|2018-12-31|          2.6|       47.6|
|2019-01-31|          2.9|       49.3|
|2019-02-28|          3.8|       51.3|
|2019-03-31|          4.7|       54.7|
|2019-04-30|          3.4|       55.8|
|2019-05-31|          3.1|       57.3|
|2019-06-30|          2.7|       55.8|
|2019-07-31|          2.2|       54.4|
|2019-08-31|          4.0|       54.5|
|2019-09-30|          5.9|       53.5|
|2019-10-31|          3.3|       50.5|
|2019-11-30|          4.3|       52.1|
|2019-12-31|          3.7|       53.8|
|2020-01-31|          2.3|       52.9|
|2020-02-29|          2.0|       50.3|
+----------+-------------+-----------+
only showing top 20 rows
[2024-10-25T08:28:30.463+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-25T08:28:30.493+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T08:28:30.496+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=indices_argentina_v02, task_id=transform, run_id=scheduled__2024-10-23T00:00:00+00:00, execution_date=20241023T000000, start_date=20241025T082818, end_date=20241025T082830
[2024-10-25T08:28:30.554+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-25T08:28:30.609+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-25T08:28:30.619+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
