[2024-10-24T22:07:03.273+0000] {processor.py:186} INFO - Started process (PID=964) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:07:03.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:07:03.276+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:07:03.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:07:03.382+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:07:03.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 7, in <module>
    spark = SparkSession.builder().appName("indices_argentina").getOrCreate()
            ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Builder' object is not callable
[2024-10-24T22:07:03.383+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:07:03.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.139 seconds
[2024-10-24T22:07:33.497+0000] {processor.py:186} INFO - Started process (PID=975) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:07:33.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:07:33.501+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:07:33.500+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:07:33.723+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:07:33.722+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 7, in <module>
    spark = SparkSession.builder().appName("indices_argentina").getOrCreate()
            ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Builder' object is not callable
[2024-10-24T22:07:33.724+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:07:33.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.257 seconds
[2024-10-24T22:08:03.796+0000] {processor.py:186} INFO - Started process (PID=986) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:08:03.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:08:03.800+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:08:03.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:08:04.117+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:08:04.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 7, in <module>
    spark = SparkSession.builder().appName("indices_argentina").getOrCreate()
            ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Builder' object is not callable
[2024-10-24T22:08:04.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:08:04.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.353 seconds
[2024-10-24T22:08:34.352+0000] {processor.py:186} INFO - Started process (PID=997) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:08:34.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:08:34.356+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:08:34.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:08:34.585+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:08:34.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 7, in <module>
    spark = SparkSession.builder().appName("indices_argentina").getOrCreate()
            ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Builder' object is not callable
[2024-10-24T22:08:34.585+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:08:34.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.258 seconds
[2024-10-24T22:09:04.820+0000] {processor.py:186} INFO - Started process (PID=1014) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:09:04.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:09:04.825+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:09:04.825+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:09:05.051+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:09:05.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 7, in <module>
    spark = SparkSession.builder().appName("indices_argentina").getOrCreate()
            ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Builder' object is not callable
[2024-10-24T22:09:05.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:09:05.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.260 seconds
[2024-10-24T22:09:17.911+0000] {processor.py:186} INFO - Started process (PID=1019) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:09:17.912+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:09:17.915+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:09:17.914+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:09:18.284+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:09:18.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:09:18.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:09:18.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.405 seconds
[2024-10-24T22:09:48.386+0000] {processor.py:186} INFO - Started process (PID=1038) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:09:48.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:09:48.391+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:09:48.391+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:09:48.658+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:09:48.656+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:09:48.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:09:48.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.311 seconds
[2024-10-24T22:10:18.897+0000] {processor.py:186} INFO - Started process (PID=1057) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:10:18.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:10:18.901+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:10:18.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:10:19.122+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:10:19.120+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:10:19.123+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:10:19.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.413 seconds
[2024-10-24T22:10:49.520+0000] {processor.py:186} INFO - Started process (PID=1076) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:10:49.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:10:49.525+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:10:49.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:10:49.897+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:10:49.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:10:49.898+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:10:49.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.405 seconds
[2024-10-24T22:11:20.145+0000] {processor.py:186} INFO - Started process (PID=1095) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:11:20.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:11:20.149+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:11:20.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:11:20.518+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:11:20.516+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:11:20.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:11:20.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.405 seconds
[2024-10-24T22:11:50.753+0000] {processor.py:186} INFO - Started process (PID=1114) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:11:50.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:11:50.757+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:11:50.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:11:51.098+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:11:51.097+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:11:51.099+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:11:51.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.372 seconds
[2024-10-24T22:12:21.342+0000] {processor.py:186} INFO - Started process (PID=1133) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:12:21.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:12:21.346+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:12:21.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:12:21.558+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:12:21.556+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:12:21.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:12:21.585+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.252 seconds
[2024-10-24T22:12:51.792+0000] {processor.py:186} INFO - Started process (PID=1152) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:12:51.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:12:51.797+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:12:51.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:12:52.009+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:12:52.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:12:52.010+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:12:52.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.410 seconds
[2024-10-24T22:13:22.419+0000] {processor.py:186} INFO - Started process (PID=1171) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:13:22.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:13:22.425+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:13:22.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:13:22.908+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:13:22.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:13:22.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:13:22.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.523 seconds
[2024-10-24T22:13:53.162+0000] {processor.py:186} INFO - Started process (PID=1190) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:13:53.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:13:53.168+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:13:53.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:13:53.594+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:13:53.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:13:53.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:13:53.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.470 seconds
[2024-10-24T22:14:23.833+0000] {processor.py:186} INFO - Started process (PID=1209) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:14:23.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:14:23.837+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:14:23.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:14:24.187+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:14:24.186+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:14:24.188+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:14:24.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.388 seconds
[2024-10-24T22:14:54.433+0000] {processor.py:186} INFO - Started process (PID=1228) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:14:54.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:14:54.437+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:14:54.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:14:54.792+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:14:54.789+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:14:54.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:14:54.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.390 seconds
[2024-10-24T22:15:25.022+0000] {processor.py:186} INFO - Started process (PID=1247) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:15:25.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:15:25.026+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:15:25.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:15:25.229+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:15:25.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:15:25.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:15:25.257+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.243 seconds
[2024-10-24T22:15:55.440+0000] {processor.py:186} INFO - Started process (PID=1266) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:15:55.443+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:15:55.448+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:15:55.447+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:15:55.810+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:15:55.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:15:55.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:15:55.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.400 seconds
[2024-10-24T22:16:26.047+0000] {processor.py:186} INFO - Started process (PID=1285) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:16:26.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:16:26.053+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:16:26.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:16:26.445+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:16:26.443+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:16:26.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:16:26.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.435 seconds
[2024-10-24T22:16:56.687+0000] {processor.py:186} INFO - Started process (PID=1304) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:16:56.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:16:56.693+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:16:56.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:16:57.045+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:16:57.043+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:16:57.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:16:57.071+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.392 seconds
[2024-10-24T22:17:27.315+0000] {processor.py:186} INFO - Started process (PID=1323) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:17:27.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:17:27.318+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:17:27.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:17:27.675+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:17:27.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:17:27.676+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:17:27.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.388 seconds
[2024-10-24T22:17:57.884+0000] {processor.py:186} INFO - Started process (PID=1342) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:17:57.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:17:57.889+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:17:57.889+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:17:58.105+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:17:58.103+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:17:58.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:17:58.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.263 seconds
[2024-10-24T22:18:28.323+0000] {processor.py:186} INFO - Started process (PID=1361) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:18:28.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:18:28.328+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:18:28.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:18:28.675+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:18:28.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:18:28.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:18:28.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.387 seconds
[2024-10-24T22:18:58.913+0000] {processor.py:186} INFO - Started process (PID=1380) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:18:58.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:18:58.918+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:18:58.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:18:59.286+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:18:59.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:18:59.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:18:59.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.401 seconds
[2024-10-24T22:19:29.529+0000] {processor.py:186} INFO - Started process (PID=1399) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:19:29.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:19:29.532+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:19:29.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:19:29.898+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:19:29.896+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:19:29.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:19:29.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.398 seconds
[2024-10-24T22:20:00.122+0000] {processor.py:186} INFO - Started process (PID=1418) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:20:00.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:20:00.126+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:20:00.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:20:00.488+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:20:00.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:20:00.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:20:00.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.410 seconds
[2024-10-24T22:20:30.702+0000] {processor.py:186} INFO - Started process (PID=1437) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:20:30.702+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:20:30.705+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:20:30.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:20:31.043+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:20:31.041+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:20:31.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:20:31.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.371 seconds
[2024-10-24T22:21:01.282+0000] {processor.py:186} INFO - Started process (PID=1456) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:21:01.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:21:01.285+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:21:01.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:21:01.506+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:21:01.504+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:21:01.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:21:01.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.385 seconds
[2024-10-24T22:21:31.882+0000] {processor.py:186} INFO - Started process (PID=1475) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:21:31.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:21:31.885+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:21:31.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:21:32.233+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:21:32.231+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:21:32.234+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:21:32.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.379 seconds
[2024-10-24T22:22:02.460+0000] {processor.py:186} INFO - Started process (PID=1494) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:22:02.461+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:22:02.463+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:22:02.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:22:02.821+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:22:02.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:22:02.822+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:22:02.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.386 seconds
[2024-10-24T22:22:33.055+0000] {processor.py:186} INFO - Started process (PID=1513) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:22:33.056+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:22:33.058+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:22:33.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:22:33.406+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:22:33.404+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:22:33.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:22:33.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.378 seconds
[2024-10-24T22:23:03.639+0000] {processor.py:186} INFO - Started process (PID=1532) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:23:03.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:23:03.643+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:23:03.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:23:04.012+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:23:04.010+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:23:04.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:23:04.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.408 seconds
[2024-10-24T22:23:34.260+0000] {processor.py:186} INFO - Started process (PID=1551) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:23:34.261+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:23:34.263+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:23:34.263+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:23:34.489+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:23:34.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:23:34.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:23:34.517+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.265 seconds
[2024-10-24T22:24:04.741+0000] {processor.py:186} INFO - Started process (PID=1570) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:24:04.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:24:04.745+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:24:04.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:24:05.203+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:24:05.200+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:24:05.204+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:24:05.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.495 seconds
[2024-10-24T22:24:35.437+0000] {processor.py:186} INFO - Started process (PID=1589) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:24:35.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:24:35.441+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:24:35.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:24:35.811+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:24:35.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:24:35.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:24:35.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.409 seconds
[2024-10-24T22:25:06.033+0000] {processor.py:186} INFO - Started process (PID=1608) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:25:06.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:25:06.038+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:25:06.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:25:06.406+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:25:06.404+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:25:06.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:25:06.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.414 seconds
[2024-10-24T22:25:36.659+0000] {processor.py:186} INFO - Started process (PID=1627) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:25:36.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:25:36.663+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:25:36.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:25:37.033+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:25:37.031+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:25:37.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:25:37.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.403 seconds
[2024-10-24T22:26:07.279+0000] {processor.py:186} INFO - Started process (PID=1652) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:26:07.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:26:07.282+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:26:07.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:26:07.634+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:26:07.632+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:26:07.635+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:26:07.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.384 seconds
[2024-10-24T22:26:37.900+0000] {processor.py:186} INFO - Started process (PID=1671) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:26:37.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:26:37.904+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:26:37.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:26:38.195+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:26:38.192+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:26:38.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:26:38.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.584 seconds
[2024-10-24T22:27:08.704+0000] {processor.py:186} INFO - Started process (PID=1690) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:27:08.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:27:08.707+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:27:08.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:27:09.106+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:27:09.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:27:09.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:27:09.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.436 seconds
[2024-10-24T22:27:39.328+0000] {processor.py:186} INFO - Started process (PID=1709) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:27:39.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:27:39.382+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:27:39.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:27:39.783+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:27:39.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:27:39.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:27:39.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.488 seconds
[2024-10-24T22:28:10.044+0000] {processor.py:186} INFO - Started process (PID=1728) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:28:10.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:28:10.049+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:28:10.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:28:10.422+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:28:10.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:28:10.423+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:28:10.444+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.406 seconds
[2024-10-24T22:28:40.655+0000] {processor.py:186} INFO - Started process (PID=1746) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:28:40.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:28:40.658+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:28:40.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:28:41.182+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:28:41.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 9, in <module>
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-10-24T22:28:41.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:28:41.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.579 seconds
[2024-10-24T22:29:28.590+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:29:28.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:29:28.595+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:29:28.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:29:33.985+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:29:34.281+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:29:34.280+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:indices_argentina_v01
[2024-10-24T22:29:34.297+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:29:34.297+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:indices_argentina_v01
[2024-10-24T22:29:34.308+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:29:34.307+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:indices_argentina_v01
[2024-10-24T22:29:34.318+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:29:34.318+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:indices_argentina_v01
[2024-10-24T22:29:34.328+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:29:34.327+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:indices_argentina_v01
[2024-10-24T22:29:34.338+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:29:34.337+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:indices_argentina_v01
[2024-10-24T22:29:34.348+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:29:34.347+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:indices_argentina_v01
[2024-10-24T22:29:34.349+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:29:34.348+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:29:34.374+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:29:34.374+0000] {dag.py:3262} INFO - Creating ORM DAG for indices_argentina_v01
[2024-10-24T22:29:34.394+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:29:34.393+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-23 00:00:00+00:00, run_after=2024-10-24 00:00:00+00:00
[2024-10-24T22:29:34.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 5.986 seconds
[2024-10-24T22:30:04.775+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:30:04.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:30:04.779+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:30:04.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:30:09.102+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:30:09.127+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:30:09.127+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:30:09.164+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:30:09.164+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-23 00:00:00+00:00, run_after=2024-10-24 00:00:00+00:00
[2024-10-24T22:30:09.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 4.418 seconds
[2024-10-24T22:30:39.380+0000] {processor.py:186} INFO - Started process (PID=469) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:30:39.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:30:39.384+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:30:39.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:30:43.753+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:30:43.778+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:30:43.777+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:30:43.805+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:30:43.805+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-23 00:00:00+00:00, run_after=2024-10-24 00:00:00+00:00
[2024-10-24T22:30:43.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 4.454 seconds
[2024-10-24T22:31:14.021+0000] {processor.py:186} INFO - Started process (PID=604) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:31:14.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:31:14.024+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:31:14.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:31:18.663+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:31:18.694+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:31:18.694+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:31:18.725+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:31:18.724+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-23 00:00:00+00:00, run_after=2024-10-24 00:00:00+00:00
[2024-10-24T22:31:18.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 4.735 seconds
[2024-10-24T22:31:48.884+0000] {processor.py:186} INFO - Started process (PID=866) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:31:48.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:31:48.887+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:31:48.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:31:54.172+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:31:54.201+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:31:54.200+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:31:54.231+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:31:54.231+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-24 00:00:00+00:00, run_after=2024-10-25 00:00:00+00:00
[2024-10-24T22:31:54.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 5.376 seconds
[2024-10-24T22:32:24.442+0000] {processor.py:186} INFO - Started process (PID=1001) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:32:24.443+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:32:24.447+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:32:24.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:32:29.785+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:32:29.817+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:32:29.817+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:32:29.999+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:32:29.998+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-24 00:00:00+00:00, run_after=2024-10-25 00:00:00+00:00
[2024-10-24T22:32:30.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 5.584 seconds
[2024-10-24T22:33:00.230+0000] {processor.py:186} INFO - Started process (PID=1135) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:33:00.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:33:00.234+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:33:00.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:33:06.377+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:33:06.411+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:33:06.410+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:33:06.589+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:33:06.589+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-24 00:00:00+00:00, run_after=2024-10-25 00:00:00+00:00
[2024-10-24T22:33:06.614+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 6.394 seconds
[2024-10-24T22:33:36.807+0000] {processor.py:186} INFO - Started process (PID=1278) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:33:36.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:33:36.811+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:33:36.810+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:33:42.983+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:33:43.249+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:33:43.249+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:33:43.303+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:33:43.302+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-24 00:00:00+00:00, run_after=2024-10-25 00:00:00+00:00
[2024-10-24T22:33:43.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 6.541 seconds
[2024-10-24T22:33:47.423+0000] {processor.py:186} INFO - Started process (PID=1514) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:33:47.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:33:47.431+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:33:47.430+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:33:56.727+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:33:56.756+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:33:56.755+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:33:56.785+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:33:56.785+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-24 00:00:00+00:00, run_after=2024-10-25 00:00:00+00:00
[2024-10-24T22:33:56.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 9.394 seconds
[2024-10-24T22:34:27.018+0000] {processor.py:186} INFO - Started process (PID=1804) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:34:27.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:34:27.022+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:34:27.022+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:34:32.049+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:34:32.074+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:34:32.074+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:34:32.102+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:34:32.101+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-24 00:00:00+00:00, run_after=2024-10-25 00:00:00+00:00
[2024-10-24T22:34:32.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 5.114 seconds
[2024-10-24T22:35:02.233+0000] {processor.py:186} INFO - Started process (PID=1944) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:35:02.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:35:02.239+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:35:02.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:35:07.205+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:35:07.266+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:35:07.265+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:35:07.433+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:35:07.432+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-24 00:00:00+00:00, run_after=2024-10-25 00:00:00+00:00
[2024-10-24T22:35:07.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 5.227 seconds
[2024-10-24T22:35:37.516+0000] {processor.py:186} INFO - Started process (PID=2079) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:35:37.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:35:37.520+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:35:37.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-10-24T22:35:42.276+0000] {processor.py:925} INFO - DAG(s) 'indices_argentina_v01' retrieved from /opt/airflow/dags/first_dag.py
[2024-10-24T22:35:42.306+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:35:42.306+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-24T22:35:42.471+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:35:42.471+0000] {dag.py:4180} INFO - Setting next_dagrun for indices_argentina_v01 to 2024-10-24 00:00:00+00:00, run_after=2024-10-25 00:00:00+00:00
[2024-10-24T22:35:42.490+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 4.982 seconds
[2024-10-24T22:36:12.698+0000] {processor.py:186} INFO - Started process (PID=2213) to work on /opt/airflow/dags/first_dag.py
[2024-10-24T22:36:12.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-10-24T22:36:12.701+0000] {logging_mixin.py:190} INFO - [2024-10-24T22:36:12.701+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
